Import Data

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("a1_data.csv")
array = np.array(df)

Define sortnregress function

Taken from: https://github.com/Scriddie/Varsortability

In [3]:
# Source: https://github.com/Scriddie/Varsortability 

from sklearn.linear_model import LinearRegression, LassoLarsIC

def sortnregress(X):
    """ Take n x d data, order nodes by marginal variance and
    regresses each node onto those with lower variance, using
    edge coefficients as structure estimates. """
    # print(X)
    LR = LinearRegression()
    LL = LassoLarsIC(criterion='bic')

    d = X.shape[1]
    # print(d)
    W = np.zeros((d, d))
    # print(W)
    increasing = np.argsort(np.var(X, axis=0))
    for k in range(1, d):
        covariates = increasing[:k]
        target = increasing[k]

        LR.fit(X[:, covariates], X[:, target].ravel())
        weight = np.abs(LR.coef_)
        LL.fit(X[:, covariates] * weight, X[:, target].ravel())
        W[covariates, target] = LL.coef_ * weight

    return W

In [24]:
output_arr = sortnregress(array)
output = pd.DataFrame(output_arr)
output

,0,1,2,3,4,5,6,7,8,9,10
0,0.000000,0.0,0.192736,0.000000,0.000000,0.000000,-0.190650,0.081409,-0.07473,-0.443256,-0.175403
1,0.783546,0.0,-0.190552,0.062237,0.000000,0.017826,0.232770,0.000000,0.13097,0.498711,0.146622
2,0.000000,0.0,0.000000,0.131269,0.161558,0.000000,-0.065559,0.000000,0.00000,0.000000,-0.032207
3,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,-0.032294,0.000000
4,0.000000,0.0,0.000000,0.248685,0.000000,0.023572,0.000000,0.000000,0.00000,0.033448,0.000000
5,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.226411,0.000000
6,0.000000,0.0,0.000000,0.000000,0.000000,0.995549,0.000000,0.000000,0.00000,0.000000,0.000000
7,0.000000,0.0,0.000000,0.000000,0.145174,0.068977,0.303719,0.000000,0.16958,-0.302512,0.075125
8,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,-0.036843,0.000000,0.00000,0.751465,0.197669
9,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
10,0.000000,0.0,0.000000,0.000000,0.042721,0.035587,-0.078033,0.000000,0.00000,0.000000,0.000000

In [22]:
output.columns = df.columns
output.index = df.columns
display(output)
output.to_csv("graph.csv", index_label="effect_on")

,A,B,C,D,E,F,G,H,I,J,K
A,0.000000,0.0,0.192736,0.000000,0.000000,0.000000,-0.190650,0.081409,-0.07473,-0.443256,-0.175403
B,0.783546,0.0,-0.190552,0.062237,0.000000,0.017826,0.232770,0.000000,0.13097,0.498711,0.146622
C,0.000000,0.0,0.000000,0.131269,0.161558,0.000000,-0.065559,0.000000,0.00000,0.000000,-0.032207
D,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,-0.032294,0.000000
E,0.000000,0.0,0.000000,0.248685,0.000000,0.023572,0.000000,0.000000,0.00000,0.033448,0.000000
F,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.226411,0.000000
G,0.000000,0.0,0.000000,0.000000,0.000000,0.995549,0.000000,0.000000,0.00000,0.000000,0.000000
H,0.000000,0.0,0.000000,0.000000,0.145174,0.068977,0.303719,0.000000,0.16958,-0.302512,0.075125
I,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,-0.036843,0.000000,0.00000,0.751465,0.197669
J,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
K,0.000000,0.0,0.000000,0.000000,0.042721,0.035587,-0.078033,0.000000,0.00000,0.000000,0.000000

In [23]:
output

,A,B,C,D,E,F,G,H,I,J,K
A,0.000000,0.0,0.192736,0.000000,0.000000,0.000000,-0.190650,0.081409,-0.07473,-0.443256,-0.175403
B,0.783546,0.0,-0.190552,0.062237,0.000000,0.017826,0.232770,0.000000,0.13097,0.498711,0.146622
C,0.000000,0.0,0.000000,0.131269,0.161558,0.000000,-0.065559,0.000000,0.00000,0.000000,-0.032207
D,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,-0.032294,0.000000
E,0.000000,0.0,0.000000,0.248685,0.000000,0.023572,0.000000,0.000000,0.00000,0.033448,0.000000
F,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.226411,0.000000
G,0.000000,0.0,0.000000,0.000000,0.000000,0.995549,0.000000,0.000000,0.00000,0.000000,0.000000
H,0.000000,0.0,0.000000,0.000000,0.145174,0.068977,0.303719,0.000000,0.16958,-0.302512,0.075125
I,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,-0.036843,0.000000,0.00000,0.751465,0.197669
J,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
K,0.000000,0.0,0.000000,0.000000,0.042721,0.035587,-0.078033,0.000000,0.00000,0.000000,0.000000