Import Data

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("a1_data.csv")
array = np.array(df)

Define sortnregress function

Taken from: https://github.com/Scriddie/Varsortability

In [42]:
# Source: https://github.com/Scriddie/Varsortability 

from sklearn.linear_model import LinearRegression, LassoLarsIC

def sortnregress(X):
    """ Take n x d data, order nodes by marginal variance and
    regresses each node onto those with lower variance, using
    edge coefficients as structure estimates. """
    # print(X)
    LR = LinearRegression()
    LL = LassoLarsIC(criterion='bic')

    d = X.shape[1]
    # print(d)
    W = np.zeros((d, d))
    # print(W)
    increasing = np.argsort(np.var(X, axis=0))
    for k in range(1, d):
        covariates = increasing[:k]
        target = increasing[k]

        LR.fit(X[:, covariates], X[:, target].ravel())
        weight = np.abs(LR.coef_)
        LL.fit(X[:, covariates] * weight, X[:, target].ravel())
        print(LL.coef_)
        W[covariates, target] = LL.coef_ 

    return W

In [75]:
output_arr = sortnregress(array)
output = pd.DataFrame(output_arr)
output

[1.]
[0.         0.77548933]
[-0.99411531  0.9977514   0.        ]
[ 0.88060387 -0.80653227  0.98455892  0.        ]
[ 1. -1.  1. -1.  1.]
[ 1. -1.  1. -1. -1. -1.]
[0.         0.         0.96680741 0.99447087 0.         0.7334166
 0.        ]
[0.49950206 0.         0.98152332 0.         0.         0.99654667
 1.00177975 0.79480387]
[0.75719754 0.         0.         0.95085056 0.         0.
 0.         0.9780951  0.        ]
[ 1.00284533 -1.00637485 -0.98528783  0.          1.0031518   0.
  0.          0.75219864  1.04587634 -0.83805729]

,0,1,2,3,4,5,6,7,8,9,10
0,0.0,0.0,0.997751,0.000000,0.000000,0.000000,-1.0,0.775489,-0.806532,-1.006375,-1.0
1,1.0,0.0,-0.994115,0.757198,0.000000,0.499502,1.0,0.000000,0.880604,1.002845,1.0
2,0.0,0.0,0.000000,0.950851,0.994471,0.000000,-1.0,0.000000,0.000000,0.000000,-1.0
3,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,-0.838057,0.0
4,0.0,0.0,0.000000,0.978095,0.000000,0.794804,0.0,0.000000,0.000000,0.752199,0.0
5,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.045876,0.0
6,0.0,0.0,0.000000,0.000000,0.000000,1.001780,0.0,0.000000,0.000000,0.000000,0.0
7,0.0,0.0,0.000000,0.000000,0.966807,0.981523,1.0,0.000000,0.984559,-0.985288,1.0
8,0.0,0.0,0.000000,0.000000,0.000000,0.000000,-1.0,0.000000,0.000000,1.003152,1.0
9,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
10,0.0,0.0,0.000000,0.000000,0.733417,0.996547,-1.0,0.000000,0.000000,0.000000,0.0

In [76]:
output.columns = df.columns
output.index = df.columns
display(output)
output.to_csv("graph.csv", index_label="effect_on")

,A,B,C,D,E,F,G,H,I,J,K
A,0.0,0.0,0.997751,0.000000,0.000000,0.000000,-1.0,0.775489,-0.806532,-1.006375,-1.0
B,1.0,0.0,-0.994115,0.757198,0.000000,0.499502,1.0,0.000000,0.880604,1.002845,1.0
C,0.0,0.0,0.000000,0.950851,0.994471,0.000000,-1.0,0.000000,0.000000,0.000000,-1.0
D,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,-0.838057,0.0
E,0.0,0.0,0.000000,0.978095,0.000000,0.794804,0.0,0.000000,0.000000,0.752199,0.0
F,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,1.045876,0.0
G,0.0,0.0,0.000000,0.000000,0.000000,1.001780,0.0,0.000000,0.000000,0.000000,0.0
H,0.0,0.0,0.000000,0.000000,0.966807,0.981523,1.0,0.000000,0.984559,-0.985288,1.0
I,0.0,0.0,0.000000,0.000000,0.000000,0.000000,-1.0,0.000000,0.000000,1.003152,1.0
J,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
K,0.0,0.0,0.000000,0.000000,0.733417,0.996547,-1.0,0.000000,0.000000,0.000000,0.0

In [92]:
import math

# convert to 0 and 1
output1 = abs(output).apply(np.ceil)
output.iloc[0,0]

0.0